Add openSUSE installation steps
OpenTabletDriver/opentabletdriver.github.io pull request #138
Opened 2023-12-20 15:10 UTC by hwsmm

Not so sure about formatting, but I guess that's it?

2023-12-20 16:25 UTC, gonX requested changes
Thanks, formatting seems fine, otherwise the tests should tell us. Just some styling concerns remaining

2023-12-20 16:25 UTC, gonX commented on site/_wiki/Install/Linux.md
> -## Fedora {#rpm}
Should probably make a new section here instead with a title like "RPM-based distributions" and then use H3's for Fedora and OpenSuSE respectively instead

2023-12-24 17:32 UTC, jamesbt365 requested changes

2023-12-24 17:32 UTC, jamesbt365 commented on site/_wiki/Install/Linux.md
> +    sudo zypper --no-gpg-check install ./OpenTabletDriver.rpm
```suggestion
    sudo zypper --no-gpg-checks install ./OpenTabletDriver.rpm
```

2023-12-24 21:12 UTC, gonX approved these changes
LGTM

2023-12-24 21:13 UTC, merged