FAQ/Linux: Add note about DE mapping virtual device in multi-monitor setups
OpenTabletDriver/opentabletdriver.github.io pull request #233
Opened 2024-12-23 00:38 UTC by TechniKris

Fixes https://github.com/OpenTabletDriver/opentabletdriver.github.io/issues/232

2025-01-03 19:26 UTC, gonX requested changes
IMO, this should be formatted a bit differently so that it is clearer that there are 2 options (remapping in the DE vs remapping in OTD). I would suggest using 2 separate h3's (`###`) for this.

2025-01-03 19:26 UTC, gonX commented on site/_wiki/FAQ/Linux.md
> +- `Right click` the area editor
```suggestion
- `Right click` the display area editor
```

2025-01-03 19:27 UTC, gonX commented on site/_wiki/FAQ/Linux.md
> +## Display mapping behaves unexpectedly on a multi-monitor setup {#DE-mapping-multi-monitor}
nitpick, this is to (hopefully) keep convention with the rest of our anchors:
```suggestion
## Display mapping behaves unexpectedly on a multi-monitor setup {#de-mapping-multi-monitor}
```
(we should really test for this)

2025-01-03 19:28 UTC, gonX commented on site/_wiki/FAQ/Linux.md
> +## Display mapping behaves unexpectedly on a multi-monitor setup {#DE-mapping-multi-monitor}
alternatively, `#desktop-environment-multi-monitor-mapping`, or similar, long is fine.

2025-01-09 03:08 UTC, TechniKris commented on site/_wiki/FAQ/Linux.md
> +- `Right click` the area editor
idk how I missed that 😅 I meant to put that in

2025-01-09 03:14 UTC, TechniKris commented on site/_wiki/FAQ/Linux.md
> +## Display mapping behaves unexpectedly on a multi-monitor setup {#DE-mapping-multi-monitor}
I made it capitalized in order to ensure the meaning is clear. Since the long form is fine I decided to go with that one

2025-01-23 00:20 UTC, gonX commented on site/_wiki/FAQ/Linux.md
> +- Find your desktop environment's tablet settings page and, if possible, map the virtual device to all screens,
```suggestion
- Find your desktop environment's tablet settings page and, if possible, map the virtual device to all screens
```

2025-01-23 00:21 UTC, gonX commented on site/_wiki/FAQ/Linux.md
> +- `Right click` the display area editor,
```suggestion
- `Right click` the display area editor
```

2025-01-23 00:21 UTC, gonX commented on site/_wiki/FAQ/Linux.md
> +- Select `Set to display` -> `Virtual Display`,
```suggestion
- Select `Set to display` -> `Virtual Display`
```

2025-01-23 00:21 UTC, gonX commented on site/_wiki/FAQ/Linux.md
> +- Save or apply your settings,
```suggestion
- Save or apply your settings
```

2025-01-23 00:22 UTC, gonX commented on site/_wiki/FAQ/Linux.md
> +- Set your intended area in your desktop environment's settings.
```suggestion
- Set your intended area in your desktop environment's settings
```

2025-01-23 00:22 UTC, gonX commented on site/_wiki/FAQ/Linux.md
> +- Set your intended area in OpenTabletDriver.
```suggestion
- Set your intended area in OpenTabletDriver
```

2025-01-24 02:15 UTC, gonX approved these changes
LGTM

2025-01-24 02:17 UTC, merged