Workflows lint markdown
OpenTabletDriver/opentabletdriver.github.io pull request #62
Opened 2023-11-28 12:03 UTC by gonX

Extends #61 

Lints markdown with [`markdownlint-cli`](https://github.com/igorshubovych/markdownlint-cli) with the GitHub action [nosborn/github-action-markdown-cli](https://github.com/nosborn/github-action-markdown-cli)

2023-11-29 06:01 UTC, gonX commented
Add how to lint to README:
`markdownlint --ignore "vendor/" --ignore _includes/tablets.md --ignore _data/plugin-repository/ . 2>&1 | less`

Integrating these ignores into the .markdownlint conf is also an option

2023-12-02 09:41 UTC, gonX commented
Rebased to work with the new Jekyll 4.x deployment

2023-12-03 13:42 UTC, X9VoiD requested changes
LGTM, just some style consistency issues.

2023-12-03 13:42 UTC, X9VoiD commented on site/_wiki/FAQ/Linux.md
> +Symptoms:
```suggestion
*Symptoms*:
```

2023-12-03 13:42 UTC, X9VoiD commented on site/_wiki/FAQ/Linux.md
> +###### Solution
```suggestion
*Solution*:
```

2023-12-03 13:50 UTC, X9VoiD commented
Worth considering if we want to add markdown linting via docker image to avoid pulling node/npm:

```
docker run -v $PWD:/workdir ghcr.io/igorshubovych/markdownlint-cli:latest "*.md"
```

> example taken from https://github.com/igorshubovych/markdownlint-cli

2023-12-03 15:38 UTC, gonX commented
> Worth considering if we want to add markdown linting via docker image to avoid pulling node/npm:
> 
> ```
> docker run -v $PWD:/workdir ghcr.io/igorshubovych/markdownlint-cli:latest "*.md"
> ```
> 
> > example taken from https://github.com/igorshubovych/markdownlint-cli

Nice, will test which is faster before merging.

2023-12-04 05:00 UTC, gonX commented
Ok, makes sense

2023-12-04 05:00 UTC, merged